Repository VariantEffect/mavedb-api, pull requests merged in 2024-09, with the labels that each got.

#295 Score set update variant validation failures
  src/mavedb/lib/mave/utils.py
  src/mavedb/routers/score_sets.py
Labels: type: bug

#297 VRS Map Integration
  alembic/versions/1d4933b4b6f7_merge_76e1e55bc5c1_and_d7e6f8c3b9dc.py
  alembic/versions/d7e6f8c3b9dc_scoreset_mapping_columns.py
  alembic/versions/f36cf612e029_additional_mapping_columns.py
  docker-compose-dev.yml
  settings/.env.template
  src/mavedb/data_providers/services.py
  src/mavedb/lib/exceptions.py
  src/mavedb/lib/logging/canonical.py
  src/mavedb/lib/permissions.py
  src/mavedb/models/enums/mapping_state.py
  src/mavedb/models/enums/user_role.py
  src/mavedb/models/mapped_variant.py
  src/mavedb/models/score_set.py
  src/mavedb/models/target_gene.py
  src/mavedb/routers/mapped_variant.py
  src/mavedb/view_models/mapped_variant.py
  src/mavedb/view_models/score_set.py
  src/mavedb/worker/jobs.py
  src/mavedb/worker/settings.py
  tests/conftest.py
  tests/helpers/constants.py
  tests/worker/test_jobs.py
Labels: type: feature

#279 Add some basic tests.
  tests/routers/test_score_set.py
  tests/view_models/test_experiment.py
  tests/view_models/test_score_set.py
  tests/view_models/test_target_sequence.py
Labels: type: tests

#306 Permissions for Sub-Resources
  src/mavedb/routers/experiment_sets.py
  src/mavedb/routers/experiments.py
  tests/routers/test_experiments.py
Labels: type: bug
