Repository VariantEffect/mavedb-api, pull requests merged in 2024-08, with the labels that each got.

#246 Support Searching for Publications via URL
  src/mavedb/lib/identifiers.py
  src/mavedb/lib/validation/publication.py
  tests/validation/test_publication.py
Labels: bug, enhancement

#255 Debug #254 problem
  src/mavedb/view_models/experiment.py
Labels: bug

#265 Make Index on Usernames Unique
  alembic/versions/44a45d616036_make_index_on_users_unique.py
  src/mavedb/models/user.py
  tests/lib/test_authentication.py
Labels: bug

#264 Fixed: Executing Jobs Were Sharing DB Sessions
  src/mavedb/worker/settings.py
  tests/conftest.py
Labels: bug

#248 Improving Application Logging
  .github/workflows/run-tests-on-push.yml
  Dockerfile.test
  docker-compose-dev.yml
  docker-compose-local.yml
  poetry.lock
  pyproject.toml
  src/mavedb/__init__.py
  src/mavedb/lib/authentication.py
  src/mavedb/lib/authorization.py
  src/mavedb/lib/contributors.py
  src/mavedb/lib/experiments.py
  src/mavedb/lib/logging.py
  src/mavedb/lib/logging/__init__.py
  src/mavedb/lib/logging/canonical.py
  src/mavedb/lib/logging/context.py
  src/mavedb/lib/logging/logged_route.py
  src/mavedb/lib/logging/models.py
  src/mavedb/lib/orcid.py
  src/mavedb/lib/permissions.py
  src/mavedb/lib/score_sets.py
  src/mavedb/lib/script_environment.py
  src/mavedb/logging/__init__.py
  src/mavedb/logging/config.py
  src/mavedb/logging/configurations/debug.yaml
  src/mavedb/logging/configurations/default.yaml
  src/mavedb/logging/configurations/dev.yaml
  src/mavedb/logging/configurations/test.yaml
  src/mavedb/logging/filters.py
  src/mavedb/logging/formatters.py
  src/mavedb/routers/access_keys.py
  src/mavedb/routers/experiment_sets.py
  src/mavedb/routers/experiments.py
  src/mavedb/routers/log.py
  src/mavedb/routers/orcid.py
  src/mavedb/routers/score_sets.py
  src/mavedb/routers/users.py
  src/mavedb/server_main.py
  src/mavedb/worker/__init__.py
  src/mavedb/worker/jobs.py
  src/mavedb/worker/settings.py
  tests/conftest.py
  tests/worker/test_jobs.py
Labels: type: enhancement
