Repository VariantEffect/mavedb-api, pull requests merged in 2024-10, with the labels that each got.

#308 Use Unchanging Identifiers for Worker Processes
  src/mavedb/routers/score_sets.py
  src/mavedb/worker/jobs.py
  tests/worker/test_jobs.py
Labels: type: bug, app: backend, app: worker

#285 Make Index on Contributors Orcid ID Unique
  alembic/versions/1cee01c42909_make_index_on_contributors_unique.py
  src/mavedb/models/contributor.py
Labels: type: bug, app: database

#287 Score Range Data Model
  alembic/versions/1cee01c42909_make_index_on_contributors_unique.py
  alembic/versions/2b6f40ea2fb6_add_score_range_column.py
  src/mavedb/lib/validation/constants/score_set.py
  src/mavedb/lib/validation/utilities.py
  src/mavedb/models/score_set.py
  src/mavedb/routers/score_sets.py
  src/mavedb/view_models/score_set.py
  tests/routers/test_score_set.py
  tests/view_models/test_score_set.py
Labels: type: feature, workstream: pillar, app: backend, app: database

#303 Require fully qualified variants for accession based score sets
  alembic/manual_migrations/migrate_single_target_endogenous_edit_transcripts_to_be_fully_qualified.py
  src/mavedb/lib/validation/dataframe.py
  tests/conftest.py
  tests/helpers/util.py
  tests/routers/data/counts_acc.csv
  tests/routers/data/scores_acc.csv
  tests/validation/test_dataframe.py
  tests/worker/data/counts_acc.csv
  tests/worker/data/scores_acc.csv
  tests/worker/test_jobs.py
Labels: type: enhancement, app: backend, app: worker

#328 Tests for Mapping Job
  src/mavedb/worker/jobs.py
  tests/conftest.py
  tests/helpers/constants.py
  tests/helpers/util.py
  tests/worker/test_jobs.py
Labels: type: tests, app: worker

#325 Add router functions to check whether users have authorization in experiment, experiment set and score set.
  src/mavedb/lib/permissions.py
  src/mavedb/routers/experiments.py
  src/mavedb/routers/permissions.py
  src/mavedb/server_main.py
  tests/routers/test_permissions.py
Labels: type: enhancement, app: backend

#337 Refresh Variant URNs Upon Score Set Publication
  alembic/manual_migrations/refresh_published_tmp_urns.py
  src/mavedb/lib/score_sets.py
  src/mavedb/routers/score_sets.py
  tests/routers/test_score_set.py
Labels: type: bug, app: backend

#342 Add Tests for UTF-8 Encoded Score and Count Files
  tests/routers/data/counts_utf8_encoded.csv
  tests/routers/data/scores_utf8_encoded.csv
  tests/routers/test_score_set.py
Labels: type: tests

#339 Bump PyYaml to ^6.0.1
  poetry.lock
  pyproject.toml
Labels: type: maintenance, app: backend
